Kill tests leftovers in case of timeout
Though now there are oddities with multiprocessing_manager.list():

    Having 1 errors! 0 tests passed. 0 tests skipped. 2.20 s elapsed (MainProcess).
    Won't run stateful tests because test data wasn't loaded.
    Traceback (most recent call last):
      File "/usr/lib/python3.12/multiprocessing/managers.py", line 813, in _callmethod
        conn = self._tls.connection
               ^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/src/ch/clickhouse/.cmake/../tests/clickhouse-test", line 3707, in <module>
        main(args)
      File "/src/ch/clickhouse/.cmake/../tests/clickhouse-test", line 3126, in main
        if len(restarted_tests) > 0:
           ^^^^^^^^^^^^^^^^^^^^
      File "<string>", line 2, in __len__
      File "/usr/lib/python3.12/multiprocessing/managers.py", line 817, in _callmethod
        self._connect()
      File "/usr/lib/python3.12/multiprocessing/managers.py", line 804, in _connect
        conn = self._Client(self._token.address, authkey=self._authkey)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/multiprocessing/connection.py", line 519, in Client
        c = SocketClient(address)
            ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/multiprocessing/connection.py", line 647, in SocketClient
        s.connect(address)
    ConnectionRefusedError: [Errno 111] Connection refused

Signed-off-by: Azat Khuzhin <a.khuzhin@semrush.com>